google_cloud_core-0.28.0-py3.6-nspkg.pth,sha256=ofmGPN1MmlzzixfrH6h3KelmTtzqTJmHlj89rIEGizE,1134
google/cloud/_helpers.py,sha256=ZmcYY42HxFuIJXHsSQkS0EjsPBBd9nvtNiJwgrBSmlo,19625
google/cloud/_http.py,sha256=hHguxxyVbZ7NaZZcojcdqqIavTwK0LkzY11W7_Bd7A4,10518
google/cloud/_testing.py,sha256=bF34SnhII8_CoGxasjhqIoHPzKbQ5SWv-zqMM9UbD0E,3435
google/cloud/client.py,sha256=nHvrlDnTDTWLCgmtiFr81TPZBiGkzmifTHsqUg2PkM8,8394
google/cloud/environment_vars.py,sha256=E_EzyV75hojlnVoaBU62aum0aIdJxynUrh3_XdHoryg,1319
google/cloud/exceptions.py,sha256=U-M3b9zS1Ks9h4oBFHILbKy8e7tC9fDv9LTsII7idc4,2200
google/cloud/iam.py,sha256=cpQbgS0Uq6_DHDkkb0FdtQKnQHG9NPLoox-O2G2qwqU,6879
google/cloud/obsolete.py,sha256=dHpIIbsRP9RETyu5x9Eq6zgcbhNpA0GyjPUHKRX62fw,1384
google/cloud/operation.py,sha256=ap-TEdDnNhDnUaRLwPlDf3CEvBcvJLBUiANiVMPvjOs,9082
google_cloud_core-0.28.0.dist-info/DESCRIPTION.rst,sha256=mAxg_a-s5LPdFYiMRtLj8PlFXO0MczCJNN5yHLbYaCU,1065
google_cloud_core-0.28.0.dist-info/METADATA,sha256=FHxO6n-kBvLzsjzigtERy5DKaEaEUZ0SCdvnkWevHx4,2031
google_cloud_core-0.28.0.dist-info/RECORD,,
google_cloud_core-0.28.0.dist-info/WHEEL,sha256=o2k-Qa-RMNIJmUdIc7KU6VWR_ErNRbWNlxDIpl7lm34,110
google_cloud_core-0.28.0.dist-info/metadata.json,sha256=5JnFWlPets8cSi_cCo2b63OobKWBTVdfIH2rstoAv8o,1118
google_cloud_core-0.28.0.dist-info/namespace_packages.txt,sha256=v8IaYqRE2a0onAGJIpZeFkkH83wXSWZRR9eOyfMwoTc,20
google_cloud_core-0.28.0.dist-info/top_level.txt,sha256=_1QvSJIhFAGfxb79D6DhB7SUw2X6T4rwnz_LLrbcD3c,7
google_cloud_core-0.28.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
google/cloud/__pycache__/_testing.cpython-35.pyc,,
google/cloud/__pycache__/obsolete.cpython-35.pyc,,
google/cloud/__pycache__/iam.cpython-35.pyc,,
google/cloud/__pycache__/_helpers.cpython-35.pyc,,
google/cloud/__pycache__/_http.cpython-35.pyc,,
google/cloud/__pycache__/environment_vars.cpython-35.pyc,,
google/cloud/__pycache__/operation.cpython-35.pyc,,
google/cloud/__pycache__/client.cpython-35.pyc,,
google/cloud/__pycache__/exceptions.cpython-35.pyc,,
